apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    url: timescaledb:5432
    user: egts
    secureJsonData:
      password: egts
    jsonData:
      database: egts
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    isDefault: true

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
