apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      host: clickhouse
      port: 9000
      username: ${CLICKHOUSE_USER:-egts}
      defaultDatabase: ${CLICKHOUSE_DB:-egts}
      protocol: native
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD:-egts}
    isDefault: true

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
